import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import '@/styles/globals.css';

const rubik = Rubik({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.variable}>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
