/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/admin/accounts/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postAdminAccountsSign-in'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/accounts/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminAccountsProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['patchAdminAccountsProfile'];
    trace?: never;
  };
  '/admin/accounts/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postAdminAccountsSign-out'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/accounts/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminAccountsSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/accounts/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminAccountsSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/accounts/revoke-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postAdminAccountsRevoke-session'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/accounts/revoke-other-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postAdminAccountsRevoke-other-sessions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/governorates/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminGovernorates'];
    put?: never;
    post: operations['postAdminGovernorates'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/governorates/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteAdminGovernoratesById'];
    options?: never;
    head?: never;
    patch: operations['patchAdminGovernoratesById'];
    trace?: never;
  };
  '/admin/skills/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminSkills'];
    put?: never;
    post: operations['postAdminSkills'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skills/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteAdminSkillsById'];
    options?: never;
    head?: never;
    patch: operations['patchAdminSkillsById'];
    trace?: never;
  };
  '/admin/files/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postAdminFilesUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/files/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteAdminFilesById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminUsersById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/cvs/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminCvs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/cvs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminCvsById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/cvs/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['patchAdminCvsByIdApprove'];
    trace?: never;
  };
  '/admin/cvs/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['patchAdminCvsByIdReject'];
    trace?: never;
  };
  '/user/accounts/sign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postUserAccountsSign-up'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/accounts/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postUserAccountsSign-in'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/accounts/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserAccountsVerify-email'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/accounts/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserAccountsSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/accounts/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserAccountsProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['patchUserAccountsProfile'];
    trace?: never;
  };
  '/user/accounts/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postUserAccountsSign-out'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/accounts/revoke-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postUserAccountsRevoke-session'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/accounts/revoke-other-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postUserAccountsRevoke-other-sessions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/governorates/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserGovernorates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/skills/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserSkills'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/files/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['postUserFilesUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/files/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['deleteUserFilesById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/cvs/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserCvs'];
    put?: never;
    post: operations['postUserCvs'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/cvs/mine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserCvsMine'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['patchUserCvsMine'];
    trace?: never;
  };
  '/user/cvs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getUserCvsById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BadRequestError:
      | {
          /** @constant */
          errorCode: 'HttpError';
          reasonCode?: string;
          message: string;
        }
      | {
          /** @constant */
          errorCode: 'LogicValidationError';
          reasonCode?: string;
          errors: string[];
        };
    /** FieldsValidationError */
    FieldsValidationError: {
      /** @constant */
      errorCode: 'FieldsValidationError';
      errors: {
        field: string;
        message: string;
      }[];
    };
    AdminAccountsSignInBody: {
      /** Format: email */
      email: string;
      password: string;
    };
    AdminAccountsSignInResponse: {
      token: string;
      user: {
        id: string;
        name: string;
        /** Format: email */
        email: string;
      };
    };
    AdminAccountsSessionResponse: {
      session: {
        id: string;
        token: string;
        expiresAt: Record<string, never> | string | number;
        userId: string;
      };
      user: {
        id: string;
        name: string;
        /** Format: email */
        email: string;
        role?: string | null;
        branchId?: string | null;
      };
    };
    AdminAccountsProfileResponse: {
      id: string;
      name: string;
      image: null | string;
      email: string;
      emailVerified: boolean;
      phoneNumber: null | string;
      phoneNumberVerified: null | boolean;
      username: null | string;
      displayUsername: null | string;
      role: null | string;
      banned: null | boolean;
      banReason: null | string;
      banExpires: null | (Record<string, never> | string | number);
      gender: null | ('Male' | 'Female');
      avatarId: null | string;
      governorateId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      avatar: {
        id: string;
        key: string;
        size: string | number;
        type: 'Image' | 'Video' | 'Other';
        isPublic: boolean;
        userId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      } | null;
      accounts: {
        id: string;
        accountId: string;
        providerId: string;
        userId: string;
        accessToken: null | string;
        refreshToken: null | string;
        idToken: null | string;
        accessTokenExpiresAt: null | (Record<string, never> | string | number);
        refreshTokenExpiresAt: null | (Record<string, never> | string | number);
        scope: null | string;
        password: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      }[];
      sessions: {
        id: string;
        token: string;
        expiresAt: Record<string, never> | string | number;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        ipAddress: null | string;
        userAgent: null | string;
        userId: string;
        impersonatedBy: null | string;
      }[];
    };
    AdminAccountsProfileUpdateBody: {
      name?: string;
      /** Format: email */
      email?: string;
      /** @description يجب ادخال رقم هاتف عراقي صحيح مثال +9647701234567 */
      phoneNumber?: string;
      /** @enum {string} */
      gender?: 'Male' | 'Female';
      /** Format: uuid */
      avatarId?: string;
      governorateId?: (string | null) | null;
    };
    AdminAccountsProfileUpdateResponse: {
      id: string;
      name: string;
      image: null | string;
      email: string;
      emailVerified: boolean;
      phoneNumber: null | string;
      phoneNumberVerified: null | boolean;
      username: null | string;
      displayUsername: null | string;
      role: null | string;
      banned: null | boolean;
      banReason: null | string;
      banExpires: null | (Record<string, never> | string | number);
      gender: null | ('Male' | 'Female');
      avatarId: null | string;
      governorateId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    AdminAccountsRevokeSessionBody: {
      token: string;
    };
    AdminAccountsRevokeSessionResponse: {
      message: string;
    };
    AdminAccountsRevokeOtherSessionsResponse: {
      message: string;
    };
    AdminGovernoratesListQuery: {
      /** @default 1 */
      page: number;
      /** @default 10 */
      pageSize: number;
      /** @default createdAt */
      sortingColumn: string;
      /** @default desc */
      sortingDirection: string;
      search?: string;
    };
    AdminGovernoratesListResponse: {
      total: number;
      data: {
        id: string;
        name: string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      }[];
    };
    AdminGovernoratesCreateBody: {
      name: string;
    };
    AdminGovernoratesCreateResponse: {
      id: string;
      name: string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    AdminGovernoratesUpdateParams: {
      /** Format: uuid */
      id: string;
    };
    AdminGovernoratesUpdateBody: {
      name: string;
    };
    AdminGovernoratesUpdateResponse: {
      id: string;
      name: string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    AdminGovernoratesDeleteParams: {
      /** Format: uuid */
      id: string;
    };
    AdminGovernoratesDeleteResponse: unknown;
    AdminSkillsListQuery: {
      /** @default 1 */
      page: number;
      /** @default 10 */
      pageSize: number;
      /** @default createdAt */
      sortingColumn: string;
      /** @default desc */
      sortingDirection: string;
      search?: string;
    };
    AdminSkillsListResponse: {
      total: number;
      data: {
        id: string;
        name: string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      }[];
    };
    AdminSkillsCreateBody: {
      name: string;
    };
    AdminSkillsCreateResponse: {
      id: string;
      name: string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    AdminSkillsUpdateParams: {
      /** Format: uuid */
      id: string;
    };
    AdminSkillsUpdateBody: {
      name: string;
    };
    AdminSkillsUpdateResponse: {
      id: string;
      name: string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    AdminSkillsDeleteParams: {
      /** Format: uuid */
      id: string;
    };
    AdminSkillsDeleteResponse: unknown;
    AdminFilesCreateBody: {
      /**
       * Format: binary
       * @default File
       */
      file: string;
      /** @enum {string} */
      type: 'Image' | 'Video' | 'Other';
      /** @enum {string} */
      isPublic: 'true' | 'false';
    };
    AdminFilesCreateResponse: {
      id: string;
      key: string;
      size: string | number;
      /** @enum {string} */
      type: 'Image' | 'Video' | 'Other';
      isPublic: boolean;
      userId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    AdminFilesDeleteResponse: unknown;
    AdminUsersListQuery: {
      /** @default 1 */
      page: number;
      /** @default 10 */
      pageSize: number;
      /** @default createdAt */
      sortingColumn: string;
      /** @default desc */
      sortingDirection: string;
      search?: string;
    };
    AdminUsersListResponse: {
      total: number;
      data: {
        id: string;
        name: string;
        image: null | string;
        email: string;
        emailVerified: boolean;
        phoneNumber: null | string;
        phoneNumberVerified: null | boolean;
        username: null | string;
        displayUsername: null | string;
        role: null | string;
        banned: null | boolean;
        banReason: null | string;
        banExpires: null | (Record<string, never> | string | number);
        gender: null | ('Male' | 'Female');
        avatarId: null | string;
        governorateId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        avatar: {
          id: string;
          key: string;
          size: string | number;
          type: 'Image' | 'Video' | 'Other';
          isPublic: boolean;
          userId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
        governorate: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
      }[];
    };
    AdminUsersGetResponse: {
      id: string;
      name: string;
      image: null | string;
      email: string;
      emailVerified: boolean;
      phoneNumber: null | string;
      phoneNumberVerified: null | boolean;
      username: null | string;
      displayUsername: null | string;
      role: null | string;
      banned: null | boolean;
      banReason: null | string;
      banExpires: null | (Record<string, never> | string | number);
      gender: null | ('Male' | 'Female');
      avatarId: null | string;
      governorateId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      avatar: {
        id: string;
        key: string;
        size: string | number;
        type: 'Image' | 'Video' | 'Other';
        isPublic: boolean;
        userId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      } | null;
      governorate: {
        id: string;
        name: string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      } | null;
    };
    AdminUsersApproveResponse: {
      message: string;
    };
    AdminUsersRejectResponse: {
      message: string;
    };
    AdminCvsListQuery: {
      /** @default 1 */
      page: number;
      /** @default 10 */
      pageSize: number;
      /** @default createdAt */
      sortingColumn: string;
      /** @default desc */
      sortingDirection: string;
      /** @enum {string} */
      status?: 'Pending' | 'Approved' | 'Rejected';
      search?: string;
    };
    AdminCvsListResponse: {
      total: number;
      data: {
        id: string;
        userId: string;
        jobTitle: string;
        experienceInYears: string | number;
        expectedSalaryMin: null | (string | number);
        expectedSalaryMax: null | (string | number);
        expectedSalaryCurrency: null | ('Iqd' | 'Usd');
        bio: string;
        githubUrl: null | string;
        linkedinUrl: null | string;
        portfolioUrl: null | string;
        availableForHire: boolean;
        availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
        workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
        /** @enum {string} */
        status: 'Pending' | 'Approved' | 'Rejected';
        views: string | number;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        user: {
          id: string;
          name: string;
          image: null | string;
          email: string;
          emailVerified: boolean;
          phoneNumber: null | string;
          phoneNumberVerified: null | boolean;
          username: null | string;
          displayUsername: null | string;
          role: null | string;
          banned: null | boolean;
          banReason: null | string;
          banExpires: null | (Record<string, never> | string | number);
          gender: null | ('Male' | 'Female');
          avatarId: null | string;
          governorateId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
          avatar: {
            id: string;
            key: string;
            size: string | number;
            type: 'Image' | 'Video' | 'Other';
            isPublic: boolean;
            userId: null | string;
            createdAt: Record<string, never> | string | number;
            updatedAt: Record<string, never> | string | number;
          } | null;
          governorate: {
            id: string;
            name: string;
            createdAt: Record<string, never> | string | number;
            updatedAt: Record<string, never> | string | number;
          } | null;
        };
        userSkills: {
          id: string;
          cvId: string;
          skillId: string;
          skill: {
            id: string;
            name: string;
            createdAt: Record<string, never> | string | number;
            updatedAt: Record<string, never> | string | number;
          };
        }[];
      }[];
    };
    AdminCvsGetResponse: {
      id: string;
      userId: string;
      jobTitle: string;
      experienceInYears: string | number;
      expectedSalaryMin: null | (string | number);
      expectedSalaryMax: null | (string | number);
      expectedSalaryCurrency: null | ('Iqd' | 'Usd');
      bio: string;
      githubUrl: null | string;
      linkedinUrl: null | string;
      portfolioUrl: null | string;
      availableForHire: boolean;
      availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
      workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
      /** @enum {string} */
      status: 'Pending' | 'Approved' | 'Rejected';
      views: string | number;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      user: {
        id: string;
        name: string;
        image: null | string;
        email: string;
        emailVerified: boolean;
        phoneNumber: null | string;
        phoneNumberVerified: null | boolean;
        username: null | string;
        displayUsername: null | string;
        role: null | string;
        banned: null | boolean;
        banReason: null | string;
        banExpires: null | (Record<string, never> | string | number);
        gender: null | ('Male' | 'Female');
        avatarId: null | string;
        governorateId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        avatar: {
          id: string;
          key: string;
          size: string | number;
          type: 'Image' | 'Video' | 'Other';
          isPublic: boolean;
          userId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
        governorate: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
      };
      userSkills: {
        id: string;
        cvId: string;
        skillId: string;
        skill: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        };
      }[];
    };
    AdminCvsApproveResponse: {
      message: string;
    };
    AdminCvsRejectResponse: {
      message: string;
    };
    UserAccountsSignUpBody: {
      name: string;
      /** Format: email */
      email: string;
      /** @description يجب ادخال رقم هاتف عراقي صحيح مثال +9647701234567 */
      phoneNumber?: string;
      /** @enum {string} */
      gender?: 'Male' | 'Female';
      birthDate?: Record<string, never> | string | number;
      /** Format: uuid */
      avatarId?: string;
      /** @description Minimum 8 characters, at least one lowercase letter, one uppercase letter, and one number */
      password: string;
    };
    UserAccountsSignUpResponse: {
      message: string;
      user: {
        id: string;
        name: string;
        /** Format: email */
        email: string;
      };
    };
    UserAccountsSignInBody: {
      /** Format: email */
      email: string;
      password: string;
    };
    UserAccountsSignInResponse: unknown;
    UserAccountsSessionResponse: {
      session: {
        id: string;
        token: string;
        expiresAt: Record<string, never> | string | number;
        userId: string;
      };
      user: {
        id: string;
        name: string;
        /** Format: email */
        email: string;
        avatar: null | {
          id: string;
          key: string;
        };
        cv: null | {
          id: string;
          userId: string;
          jobTitle: string;
          experienceInYears: string | number;
          expectedSalaryMin: null | (string | number);
          expectedSalaryMax: null | (string | number);
          expectedSalaryCurrency: null | ('Iqd' | 'Usd');
          bio: string;
          githubUrl: null | string;
          linkedinUrl: null | string;
          portfolioUrl: null | string;
          availableForHire: boolean;
          availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
          workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
          status: 'Pending' | 'Approved' | 'Rejected';
          views: string | number;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        };
      };
    };
    UserAccountsProfileResponse: {
      id: string;
      name: string;
      image: null | string;
      email: string;
      emailVerified: boolean;
      phoneNumber: null | string;
      phoneNumberVerified: null | boolean;
      username: null | string;
      displayUsername: null | string;
      role: null | string;
      banned: null | boolean;
      banReason: null | string;
      banExpires: null | (Record<string, never> | string | number);
      gender: null | ('Male' | 'Female');
      avatarId: null | string;
      governorateId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      avatar: {
        id: string;
        key: string;
        size: string | number;
        type: 'Image' | 'Video' | 'Other';
        isPublic: boolean;
        userId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      } | null;
      accounts: {
        id: string;
        accountId: string;
        providerId: string;
        userId: string;
        accessToken: null | string;
        refreshToken: null | string;
        idToken: null | string;
        accessTokenExpiresAt: null | (Record<string, never> | string | number);
        refreshTokenExpiresAt: null | (Record<string, never> | string | number);
        scope: null | string;
        password: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
      }[];
      sessions: {
        id: string;
        token: string;
        expiresAt: Record<string, never> | string | number;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        ipAddress: null | string;
        userAgent: null | string;
        userId: string;
        impersonatedBy: null | string;
      }[];
    };
    UserAccountsProfileUpdateBody: {
      name?: string;
      /** @enum {string} */
      gender?: 'Male' | 'Female';
      birthDate?: Record<string, never> | string | number;
      /** Format: uuid */
      avatarId?: string;
      governorateId?: (string | null) | null;
    };
    UserAccountsProfileUpdateResponse: {
      id: string;
      name: string;
      image: null | string;
      email: string;
      emailVerified: boolean;
      phoneNumber: null | string;
      phoneNumberVerified: null | boolean;
      username: null | string;
      displayUsername: null | string;
      role: null | string;
      banned: null | boolean;
      banReason: null | string;
      banExpires: null | (Record<string, never> | string | number);
      gender: null | ('Male' | 'Female');
      avatarId: null | string;
      governorateId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    UserAccountsRevokeSessionBody: {
      token: string;
    };
    UserAccountsRevokeSessionResponse: {
      message: string;
    };
    UserAccountsRevokeOtherSessionsResponse: {
      message: string;
    };
    VerifyEmailQuery: {
      token: string;
    };
    UserGovernoratesListResponse: {
      id: string;
      name: string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    }[];
    UserSkillsListResponse: {
      id: string;
      name: string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    }[];
    UserFilesCreateBody: {
      /**
       * Format: binary
       * @default File
       */
      file: string;
      /** @enum {string} */
      type: 'Image' | 'Video' | 'Other';
      /** @enum {string} */
      isPublic: 'true' | 'false';
    };
    UserFilesCreateResponse: {
      id: string;
      key: string;
      size: string | number;
      /** @enum {string} */
      type: 'Image' | 'Video' | 'Other';
      isPublic: boolean;
      userId: null | string;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
    };
    UserFilesDeleteResponse: unknown;
    UserCvsListQuery: {
      /** @default 1 */
      page: number;
      /** @default 10 */
      pageSize: number;
      /** @default createdAt */
      sortingColumn: string;
      /** @default desc */
      sortingDirection: string;
      search?: string;
      skillIds?: string[] | string;
      /** Format: uuid */
      governorateId?: string;
      /** @enum {string} */
      availabilityType?: 'FullTime' | 'PartTime' | 'Freelance';
      /** @enum {string} */
      workLocationType?: 'OnSite' | 'Remote' | 'Hybrid';
      experienceMin?: number;
      experienceMax?: number;
      salaryMin?: number;
      salaryMax?: number;
      /** @enum {string} */
      salaryCurrency?: 'Iqd' | 'Usd';
      availableForHire?: boolean;
    };
    UserCvsListResponse: {
      total: number;
      data: {
        id: string;
        userId: string;
        jobTitle: string;
        experienceInYears: string | number;
        bio: string;
        githubUrl: null | string;
        linkedinUrl: null | string;
        portfolioUrl: null | string;
        availableForHire: boolean;
        availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
        workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
        /** @enum {string} */
        status: 'Pending' | 'Approved' | 'Rejected';
        views: string | number;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        user: {
          id: string;
          name: string;
          image: null | string;
          email: string;
          emailVerified: boolean;
          phoneNumber: null | string;
          phoneNumberVerified: null | boolean;
          username: null | string;
          displayUsername: null | string;
          role: null | string;
          banned: null | boolean;
          banReason: null | string;
          banExpires: null | (Record<string, never> | string | number);
          gender: null | ('Male' | 'Female');
          avatarId: null | string;
          governorateId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
          avatar: {
            id: string;
            key: string;
            size: string | number;
            type: 'Image' | 'Video' | 'Other';
            isPublic: boolean;
            userId: null | string;
            createdAt: Record<string, never> | string | number;
            updatedAt: Record<string, never> | string | number;
          } | null;
          governorate: {
            id: string;
            name: string;
            createdAt: Record<string, never> | string | number;
            updatedAt: Record<string, never> | string | number;
          } | null;
        };
        userSkills: {
          id: string;
          cvId: string;
          skillId: string;
          skill: {
            id: string;
            name: string;
            createdAt: Record<string, never> | string | number;
            updatedAt: Record<string, never> | string | number;
          };
        }[];
      }[];
    };
    UserCvsGetResponse: {
      id: string;
      userId: string;
      jobTitle: string;
      experienceInYears: string | number;
      bio: string;
      githubUrl: null | string;
      linkedinUrl: null | string;
      portfolioUrl: null | string;
      availableForHire: boolean;
      availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
      workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
      /** @enum {string} */
      status: 'Pending' | 'Approved' | 'Rejected';
      views: string | number;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      user: {
        id: string;
        name: string;
        image: null | string;
        email: string;
        emailVerified: boolean;
        phoneNumber: null | string;
        phoneNumberVerified: null | boolean;
        username: null | string;
        displayUsername: null | string;
        role: null | string;
        banned: null | boolean;
        banReason: null | string;
        banExpires: null | (Record<string, never> | string | number);
        gender: null | ('Male' | 'Female');
        avatarId: null | string;
        governorateId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        avatar: {
          id: string;
          key: string;
          size: string | number;
          type: 'Image' | 'Video' | 'Other';
          isPublic: boolean;
          userId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
        governorate: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
      };
      userSkills: {
        id: string;
        cvId: string;
        skillId: string;
        skill: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        };
      }[];
    };
    UserCvsCreateBody: {
      profile?: {
        name?: string;
        /** @enum {string} */
        gender?: 'Male' | 'Female';
        birthDate?: Record<string, never> | string | number;
        /** Format: uuid */
        avatarId?: string;
        governorateId?: (string | null) | null;
      };
      jobTitle: string;
      experienceInYears: number;
      expectedSalaryMin?: number;
      expectedSalaryMax?: number;
      /** @enum {string} */
      expectedSalaryCurrency?: 'Iqd' | 'Usd';
      availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
      workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
      bio: string;
      /** Format: uri */
      githubUrl?: string;
      /** Format: uri */
      linkedinUrl?: string;
      /** Format: uri */
      portfolioUrl?: string;
      availableForHire: boolean;
      skillIds: string[];
    };
    UserCvsCreateResponse: {
      id: string;
      userId: string;
      jobTitle: string;
      experienceInYears: string | number;
      bio: string;
      githubUrl: null | string;
      linkedinUrl: null | string;
      portfolioUrl: null | string;
      availableForHire: boolean;
      availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
      workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
      /** @enum {string} */
      status: 'Pending' | 'Approved' | 'Rejected';
      views: string | number;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      user: {
        id: string;
        name: string;
        image: null | string;
        email: string;
        emailVerified: boolean;
        phoneNumber: null | string;
        phoneNumberVerified: null | boolean;
        username: null | string;
        displayUsername: null | string;
        role: null | string;
        banned: null | boolean;
        banReason: null | string;
        banExpires: null | (Record<string, never> | string | number);
        gender: null | ('Male' | 'Female');
        avatarId: null | string;
        governorateId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        avatar: {
          id: string;
          key: string;
          size: string | number;
          type: 'Image' | 'Video' | 'Other';
          isPublic: boolean;
          userId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
        governorate: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
      };
      userSkills: {
        id: string;
        cvId: string;
        skillId: string;
        skill: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        };
      }[];
    };
    UserCvsUpdateBody: {
      profile?: {
        name?: string;
        /** @enum {string} */
        gender?: 'Male' | 'Female';
        birthDate?: Record<string, never> | string | number;
        /** Format: uuid */
        avatarId?: string;
        governorateId?: (string | null) | null;
      };
      jobTitle?: string;
      experienceInYears?: number;
      expectedSalaryMin?: number;
      expectedSalaryMax?: number;
      /** @enum {string} */
      expectedSalaryCurrency?: 'Iqd' | 'Usd';
      availabilityTypes?: ('FullTime' | 'PartTime' | 'Freelance')[];
      workLocationTypes?: ('OnSite' | 'Remote' | 'Hybrid')[];
      bio?: string;
      /** Format: uri */
      githubUrl?: string;
      /** Format: uri */
      linkedinUrl?: string;
      /** Format: uri */
      portfolioUrl?: string;
      availableForHire?: boolean;
      skillIds?: string[];
    };
    UserCvsUpdateResponse: {
      id: string;
      userId: string;
      jobTitle: string;
      experienceInYears: string | number;
      bio: string;
      githubUrl: null | string;
      linkedinUrl: null | string;
      portfolioUrl: null | string;
      availableForHire: boolean;
      availabilityTypes: ('FullTime' | 'PartTime' | 'Freelance')[];
      workLocationTypes: ('OnSite' | 'Remote' | 'Hybrid')[];
      /** @enum {string} */
      status: 'Pending' | 'Approved' | 'Rejected';
      views: string | number;
      createdAt: Record<string, never> | string | number;
      updatedAt: Record<string, never> | string | number;
      user: {
        id: string;
        name: string;
        image: null | string;
        email: string;
        emailVerified: boolean;
        phoneNumber: null | string;
        phoneNumberVerified: null | boolean;
        username: null | string;
        displayUsername: null | string;
        role: null | string;
        banned: null | boolean;
        banReason: null | string;
        banExpires: null | (Record<string, never> | string | number);
        gender: null | ('Male' | 'Female');
        avatarId: null | string;
        governorateId: null | string;
        createdAt: Record<string, never> | string | number;
        updatedAt: Record<string, never> | string | number;
        avatar: {
          id: string;
          key: string;
          size: string | number;
          type: 'Image' | 'Video' | 'Other';
          isPublic: boolean;
          userId: null | string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
        governorate: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        } | null;
      };
      userSkills: {
        id: string;
        cvId: string;
        skillId: string;
        skill: {
          id: string;
          name: string;
          createdAt: Record<string, never> | string | number;
          updatedAt: Record<string, never> | string | number;
        };
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'postAdminAccountsSign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminAccountsSignInBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminAccountsSignInBody'];
        'multipart/form-data': components['schemas']['AdminAccountsSignInBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccountsSignInResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminAccountsProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccountsProfileResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchAdminAccountsProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminAccountsProfileUpdateBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminAccountsProfileUpdateBody'];
        'multipart/form-data': components['schemas']['AdminAccountsProfileUpdateBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccountsProfileUpdateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postAdminAccountsSign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminAccountsSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccountsSessionResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminAccountsSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postAdminAccountsRevoke-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminAccountsRevokeSessionBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminAccountsRevokeSessionBody'];
        'multipart/form-data': components['schemas']['AdminAccountsRevokeSessionBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccountsRevokeSessionResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postAdminAccountsRevoke-other-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminAccountsRevokeOtherSessionsResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminGovernorates: {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortingColumn: string;
        sortingDirection: string;
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminGovernoratesListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  postAdminGovernorates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminGovernoratesCreateBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminGovernoratesCreateBody'];
        'multipart/form-data': components['schemas']['AdminGovernoratesCreateBody'];
      };
    };
    responses: {
      /** @description Response for status 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminGovernoratesCreateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  deleteAdminGovernoratesById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 204 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminGovernoratesDeleteResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchAdminGovernoratesById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminGovernoratesUpdateBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminGovernoratesUpdateBody'];
        'multipart/form-data': components['schemas']['AdminGovernoratesUpdateBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminGovernoratesUpdateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminSkills: {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortingColumn: string;
        sortingDirection: string;
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSkillsListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  postAdminSkills: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminSkillsCreateBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminSkillsCreateBody'];
        'multipart/form-data': components['schemas']['AdminSkillsCreateBody'];
      };
    };
    responses: {
      /** @description Response for status 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSkillsCreateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  deleteAdminSkillsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 204 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSkillsDeleteResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchAdminSkillsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminSkillsUpdateBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminSkillsUpdateBody'];
        'multipart/form-data': components['schemas']['AdminSkillsUpdateBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSkillsUpdateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  postAdminFilesUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminFilesCreateBody'];
        'application/x-www-form-urlencoded': components['schemas']['AdminFilesCreateBody'];
        'multipart/form-data': components['schemas']['AdminFilesCreateBody'];
      };
    };
    responses: {
      /** @description Response for status 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminFilesCreateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  deleteAdminFilesById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 204 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminFilesDeleteResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminUsers: {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortingColumn: string;
        sortingDirection: string;
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUsersListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminUsersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUsersGetResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminCvs: {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortingColumn: string;
        sortingDirection: string;
        status?: 'Pending' | 'Approved' | 'Rejected';
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCvsListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getAdminCvsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCvsGetResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchAdminCvsByIdApprove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCvsApproveResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchAdminCvsByIdReject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCvsRejectResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postUserAccountsSign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserAccountsSignUpBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserAccountsSignUpBody'];
        'multipart/form-data': components['schemas']['UserAccountsSignUpBody'];
      };
    };
    responses: {
      /** @description Response for status 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsSignUpResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postUserAccountsSign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserAccountsSignInBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserAccountsSignInBody'];
        'multipart/form-data': components['schemas']['UserAccountsSignInBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsSignInResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'getUserAccountsVerify-email': {
    parameters: {
      query: {
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserAccountsSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsSessionResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserAccountsProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsProfileResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchUserAccountsProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserAccountsProfileUpdateBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserAccountsProfileUpdateBody'];
        'multipart/form-data': components['schemas']['UserAccountsProfileUpdateBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsProfileUpdateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postUserAccountsSign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postUserAccountsRevoke-session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserAccountsRevokeSessionBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserAccountsRevokeSessionBody'];
        'multipart/form-data': components['schemas']['UserAccountsRevokeSessionBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsRevokeSessionResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  'postUserAccountsRevoke-other-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserAccountsRevokeOtherSessionsResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserGovernorates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserGovernoratesListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserSkills: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSkillsListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  postUserFilesUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserFilesCreateBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserFilesCreateBody'];
        'multipart/form-data': components['schemas']['UserFilesCreateBody'];
      };
    };
    responses: {
      /** @description Response for status 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserFilesCreateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  deleteUserFilesById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 204 */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserFilesDeleteResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserCvs: {
    parameters: {
      query: {
        page: number;
        pageSize: number;
        sortingColumn: string;
        sortingDirection: string;
        search?: string;
        skillIds?: string[] | string;
        governorateId?: string;
        availabilityType?: 'FullTime' | 'PartTime' | 'Freelance';
        workLocationType?: 'OnSite' | 'Remote' | 'Hybrid';
        experienceMin?: number;
        experienceMax?: number;
        salaryMin?: number;
        salaryMax?: number;
        salaryCurrency?: 'Iqd' | 'Usd';
        availableForHire?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserCvsListResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  postUserCvs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCvsCreateBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserCvsCreateBody'];
        'multipart/form-data': components['schemas']['UserCvsCreateBody'];
      };
    };
    responses: {
      /** @description Response for status 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserCvsCreateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserCvsMine: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserCvsGetResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  patchUserCvsMine: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCvsUpdateBody'];
        'application/x-www-form-urlencoded': components['schemas']['UserCvsUpdateBody'];
        'multipart/form-data': components['schemas']['UserCvsUpdateBody'];
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserCvsUpdateResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
  getUserCvsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserCvsGetResponse'];
        };
      };
      /** @description Response for status 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description Response for status 422 */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldsValidationError'];
        };
      };
    };
  };
}
